mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
urlpatterns = [
    url(r'^game/', include('polls.urls' ,namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    
]

mysite/polls/urls.py
# author sri harsha ganja
# ganjash

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home,name='home'),
    url(r'^identify/$', views.identify,name='identify'),
    url(r'^detail/$',views.loginn,name='detail'),
    url(r'^logout/$',views.logout_view,name='logout'),
    url(r'^home/$', views.home,name='home'),
    url(r'^welcome/$',views.welcome,name='welcome'),
    url(r'^play/$',views.play,name='play'),
    url(r'^phase1/$',views.phase1,name='phase1'),
    url(r'^phase2/$',views.phase2,name='phase2'),
    url(r'^stats/$',views.stats,name='stats'),
    url(r'^help/$',views.help,name='help'),
    #url(r'^phase1/(?P<query>\w?)',views.phase1,name='phase1'),
]

mysite/polls/models.py
# author sri harsha ganja
# ganjash

from django.db import models
# Create your models here.

class Question(models.Model):
     question_text = models.CharField(max_length=200)
     pub_date = models.DateTimeField('date published')
     
     def __str__(self):              # __unicode__ on Python 2
        return self.question_text
     
class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):              # __unicode__ on Python 2
        return self.choice_text

mysite/polls/views.py
# author sri harsha ganja
# ganjash

import pdb
from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext,loader
import random,json
# Create your views here.
from django.contrib.auth import authenticate, login , logout
from django.template.context import RequestContext
import logging

track_css = []

def loginn(request):
    return HttpResponse(render(request,'polls/login.html'))

def home(request):
    return HttpResponse(render(request,'polls/home.html'))

def welcome(request):
    if(request.POST.get('query') is not None):
        #pdb.set_trace()
        stat = json.loads(request.POST.get('query'))
        request.session['stat']=stat
        request.session.modified = True
    
    return HttpResponse(render(request,'polls/welcome2.html' ))
    #return HttpResponse(render(request,'polls/phase.html' ))

def help(request):
    return HttpResponse(render(request,'polls/welcome.html' ))


def play(request):
    if('button_css' not in request.session.keys()):
        request.session['button_css']={'usa':'btn pagemenu','egypt':'btn pagemenu','canada':'btn pagemenu','russia':'btn pagemenu','uk':'btn pagemenu','china':'btn pagemenu','france':'btn pagemenu','india':'btn pagemenu','italy':'btn pagemenu','aust':'btn pagemenu','monument':'btn pagemenu','flag':'btn pagemenu','currency':'btn pagemenu','animal':'btn pagemenu'}    
    but = request.session['button_css']
    
    template = loader.get_template('polls/play.html')
    context = RequestContext(request,{'but':but,})
    #pdb.set_trace()
    return HttpResponse(template.render(context))
    
    #return HttpResponse(render(request,'polls/play.html'))
def stats(request):
    #pdb.set_trace()
    if('stat' not in request.session.keys()):
        request.session['stat']=[0,0,0,0]    
    stat = request.session['stat']
    template = loader.get_template('polls/stats.html')
    context = RequestContext(request,{'stat':stat,})
    #pdb.set_trace()
    return HttpResponse(template.render(context))




def phase1(request):
    #pdb.set_trace()
    #logging.debug("hiii I am logger")
    #pdb.set_trace();
#[ ,135, 819, 159, 198, 308, 46, 521, 809, 567, 220]
    
    #logging.debug(request.POST.lists)
    aust = {'m':[3,'asf123.jpg'],'f':[1,'23as3ykt.png'],'c':[2,'fgdthfxs.jpg'],'a':[4,'sa324fd.jpg'],'n':'aust'}
    usa ={'m':[1,'izs015583.jpg'],'f':[2,'mu67fg.jpg'],'c':[3,'ncBXjzb7i.jpg'],'a':[4,'sdefg.jpg'],'n':'usa'}
    canada ={'m':[4,'dsh5784.jpg'],'f':[2,'ht34df68.jpg'],'c':[3,'fdbdfvasd.jpg'],'a':[1,'tjtd54.jpg'],'n':'canada'}
    china ={'m':[4,'hmg4359gv.jpg'],'f':[1,'sgfh87067.jpg'],'c':[2,'oirthgio3.jpg'],'a':[3,'bvm685.jpg'],'n':'china'}
    egypt ={'m':[2,'ytzx23.jpg'],'f':[1,'tyd213r.jpg'],'c':[3,'jhk234.jpg'],'a':[4,'ghrrpzxc.jpg'],'n':'egypt'}
    france ={'m':[4,'gfhopo1123.jpg'],'f':[2,'adhrfd.png'],'c':[1,'cu09o3e.jpg'],'a':[3,'ghj89947.jpg'],'n':'france'}
    india ={'m':[2,'pzoqew.jpg'],'f':[3,'ggdfhit12.jpg'],'c':[1,'e78sdf.jpg'],'a':[4,'dsfg32498.jpg'],'n':'india'}
    italy ={'m':[4,'hgoiucvb.jpg'],'f':[3,'hgjerop.png'],'c':[1,'ure93ioe.jpg'],'a':[2,'fsdhyu.jpg'],'n':'italy'}
    russia ={'m':[1,'98r535.jpg'],'f':[3,'nbodfio.png'],'c':[4,'hrt46rf.jpg'],'a':[2,'jgjhgh897.jpg'],'n':'russia'}
    uk ={'m':[4,'fdghue.jpg'],'f':[3,'dsgffd.jpg'],'c':[2,'wh434ni.jpg'],'a':[1,'sdfpoiy.jpg'],'n':'uk'}
    #messages.info(request, 'Three credits remain in your account.')
    #country = {'australia':aust,'usa':usa}
    country = {'aust':aust,'usa':usa,'canada':canada,'china':china,'egypt':egypt,'france':france,'india':india,'italy':italy,'russia':russia,'uk':uk}
    #if(request.session[])
    
    coords = {'usa':['usamap.png',['635px','322px'],['592px','381px'],['541px','398px'],['115px','582px']],
                  'canada':['canadamap.png',['201px','336px'],['377px','565px'],['420px','600px'],['441px','648px']],
                  'china':['chinamap.png',['257px','371px'],['326px','412px'],['434px','371px'],['448px','396px']],
                   'india':['indiamap.png',['226px','299px'],['255px','272px'],['256px','320px'],['394px','394px']],
                  'uk':['ukmap.png',['428px','514px'],['479px','525px'],['470px','579px'],['419px','572px']],
                   'russia':['russiamap.png',['134px','435px'],['180px','462px'],['252px','527px'],['132px','484px']],
                   'aust':['australiamap.png',['248px','304px'],['206px','307px'],['195px','355px'],['257px','457px']],
                   'france':['francemap.png',['561px','232px'],['402px','300px'],['351px','290px'],['367px','329px']],
                   'egypt':['egyptmap.png',['370px','238px'],['410px','234px'],['375px','277px'],['190px','440px']],
                   'italy':['italymap.png',['265px','290px'],['320px','397px'],['340px','430px'],['369px','455px']]
                   }

    key = ''
    if('query' not in request.session.keys()):
        request.session['query']='usa'
    
    if(request.GET.get('phase2') is not None):         
        if('available' not in request.session.keys()):
            select = random.sample(country.keys(),4)
            hashh = random.sample(range(1,5),4)
            dictt = []
            for i in xrange(4):
                dictt.append([select[i],hashh[i],country[select[i]]['m'][1]] )
            request.session['available']=[dictt]
            dictt = []
            select = random.sample(country.keys(),4)
            hashh = random.sample(range(1,5),4)
            for i in xrange(4):
                dictt.append([select[i],hashh[i],country[select[i]]['f'][1]] )
            request.session['available'].append(dictt)
            dictt = []
            select = random.sample(country.keys(),4)
            hashh = random.sample(range(1,5),4) 
            for i in xrange(4):
                dictt.append([select[i],hashh[i],country[select[i]]['c'][1]] )
            request.session['available'].append(dictt)
            dictt = []
            select = random.sample(country.keys(),4)
            hashh = random.sample(range(1,5),4)
            for i in xrange(4):
                dictt.append([select[i],hashh[i],country[select[i]]['a'][1]] )
            request.session['available'].append(dictt)
            request.session['artifacts'] = ['monument','flag','currency','animal']
            request.session.modified = True
        #if('monument' not in request.session.keys()):
        #    dictt = {}
        #    for i in xrange(4):
        #        dictt[select[i]] = [hashh[i],country[select[i]]['m'][1],0]
        #    request.session['available']=[dictt]
        
        #if('flag' not in request.session.keys()):
        #    dictt = {}
        #    for i in xrange(4):
        #        dictt[select[i]] = [hashh[i],country[select[i]]['f'][1],0]
        #    request.session['available'].append(dictt)
        # 
        #if('currency' not in request.session.keys()):
        #    dictt = {}
        #    for i in xrange(4):
        #        dictt[select[i]] = [hashh[i],country[select[i]]['c'][1],0]
        #    request.session['available'].append(dictt)
        #    #request.session['currency']=dictt
        #
        #if('animal' not in request.session.keys()):
        #    dictt = {}
        #    for i in xrange(4):
        #        dictt[select[i]] = [hashh[i],country[select[i]]['a'][1],0]
        #    request.session['available'].append(dictt)
            #request.session['animal']=dictt
            
        
        #return HttpResponse(render(request,'polls/phase1.html'))
    
            #dictt[select[i]] = [hashh[i],country[select[i]]['m'][1]]

    #request.session['sample']='sample_reply'
    #if(request.POST.get('query') is not None):
    #cntry= request.POST.get('query')
    #    logging.debug(request.POST.lists)
    #return HttpResponse(cntry, content_type="text/plain")
    #if(request.POST.lists() != []):
    #    cntry = request.POST.lists;
    #    return HttpResponse(cntry, content_type="text/plain")
    if(request.GET.get('query') is not None):
        cntry = request.GET.get('query')
    #    #return HttpResponse(str(country[cntry]),content_type="text/plain")
        return HttpResponse(json.dumps(country[cntry]), content_type="application/json")
    
    if(request.GET.get('country') is not None):
        key = request.GET.get('country')

            #   
    if(request.POST.get('query') is not None):
        cntry = request.POST.get('query')
        request.session['button_css'][cntry]='btn2 pagemenu'
        request.session.modified = True
        
        #return HttpResponse(str(country[cntry]),content_type="text/plain")
        return HttpResponse(json.dumps(country[cntry]), content_type="application/json")
    #pdb.set_trace();
    n =4 #no.of unique images to be matched
    id_list = random.sample(range(1,100),n);
    template = loader.get_template('polls/phasex.html')
    #template = loader.get_template('polls/phasex2.html')
    #template = loader.get_template('polls/phasex3.html')
    #template = loader.get_template('polls/phasex4.html')
    #template = loader.get_template('polls/phasex5.html')
    #template = loader.get_template('polls/phasex6.html')
    #template = loader.get_template('polls/phasex7.html')
    #template = loader.get_template('polls/phasex8.html')
    #template = loader.get_template('polls/phasex9.html')
    
    # m map, f flag, c currency, a animal , n name
    template = loader.get_template('polls/phasex.html')
    context = RequestContext(request,{'id_list':id_list,'country':country[key],'coords':coords[key],'key':key,})
    return HttpResponse(template.render(context))
    
def phase2(request):
    #pdb.set_trace()
    key = request.session.get('key')
    #pdb.set_trace()
    if('validator' not in request.session.keys()):
    #    request.session['selector']=0
        request.session['validator']=[['m',-2],['f',-2],['c',-2],['a',-2]]

    if(request.GET.get('artifacts') is not None):
        key = request.GET.get('artifacts')

mysite/polls/templates/polls/asdf.html
<!-- author sri harsha ganja
     ganjash -->
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=windows-1252" http-equiv="content-type">
    <title>usa map</title>
    <style>
.circle {
border-top-left-radius: 50%;
border-top-right-radius: 50%;
border-bottom-right-radius: 50%;
border-bottom-left-radius: 50%;

}
</style>
  </head>
  <body>
    <div style="background-image: url(file:///home/harsha/Desktop/usamap.png); height: 469px; width: 702px;">
      <div>
        <div class="circle" style="background-color: #ff9966; width: 39px; position: absolute; left: 582px; top: 201px; z-index: 2; height: 39px;"><br>
        </div>
        <div class="circle" style="background-color: #ff9966; width: 39px; position: absolute; left: 540px; top: 201px; z-index: 2; height: 39px;""></div>
        <div class="circle" style="background-color: #ff9966; width: 39px; position: absolute; left: 520px; top: 191px; z-index: 2; height: 39px;"><br>
        </div>
        <div class="circle" style="background-color: rgb(255, 153, 102); width: 39px; position: absolute; left: 103px; top: 417px; z-index: 2; height: 39px;"><br>
        </div>
      </div>
    </div>
  </body>
</html>

mysite/polls/templates/polls/login.html
<!-- author sri harsha ganja
     ganjash -->
{% extends "polls/base.html" %}
{% block titlename %}
Log in
{% endblock %}
{% block form %}
	<form action="{% url 'polls:identify'  %}" method="post">
		{% csrf_token %} <br><br><br><br><br><br><br><br>
													<big style="font-weight: bold;"><big>Login</big></big><br><br>
															<big>username: <input type="text" name="username"
																value="{{ username}}" /><br /> password: <input
																type="password" name="password" value="" /><br />
														</big> <input type="submit" value="Log In" />
	</form>
{% endblock %}

mysite/polls/templates/polls/stats.html
<!-- author sri harsha ganja
     ganjash -->
{% extends "polls/base.html" %} {% block extras %}
{% load staticfiles %}
{% load poll_extras %}
<text
	style="color: black; height: 24px; font-weight: bold; text-decoration: underline; margin-top: 0px; text-align: right; position: relative; right: 500px;">
	
<a href="{% url 'polls:welcome'  %}"> <big>Home</big></a> 
</text>
<text
	style="color: black; height: 24px; font-weight: bold; text-decoration: underline; position: relative; left: 500px; margin-top: 0px; text-align: right;">
<a href="{% url 'polls:logout'  %}"> <big>Logout</big></a> </text>
{% endblock %} {% block content %}
<div style="background-image: url({%static 'polls/images/stars_back.png' %}); background-position: center top; margin-left: 250px; width: 756px; margin-top: 0px; height: 400px;">
<div style="height: 51px;">

	<p>&nbsp;
		<big style="text-decoration: underline; color: white;"> <big style="margin-top: 0px; height: 51px;"><big>Statistics!!!</big></big></big>
	</p>
</div><br>
<br>
<br>
<table style="text-align: left; background-color: transparent; width: 413px; margin-left: 240px;" border="0" cellpadding="10" cellspacing="2">
  <tbody style="width: 407px;">
    <tr>
      <td style="vertical-align: top; width: 128px; color: white;">Monuments</td>
      <td style="vertical-align: top; width: 239px;">{% for i in stat.0|get_range %}
      <img style = "width: 35px;height: 35px;" src ="{% static 'polls/images/star.png' %}"></img>
      {% endfor %}
      </td>
    </tr>
    <tr>
      <td style="vertical-align: top; width: 128px; color: white;">Flags<br>
      </td>
      <td style="vertical-align: top; width: 239px;">{% for i in stat.1|get_range %}
            <img style = "width: 35px;height: 35px;" src ="{% static 'polls/images/star.png' %}"></img>
            {% endfor %}
      </td>
    </tr>
    <tr>
      <td style="vertical-align: top; width: 128px; color: white;">Animals<br>
      </td>
      <td style="vertical-align: top; width: 239px;">{% for i in stat.2|get_range %}
            <img style = "width: 35px;height: 35px;" src ="{% static 'polls/images/star.png' %}"></img>
            {% endfor %}
      </td>
    </tr>
    <tr>
      <td style="vertical-align: top; width: 128px; color: white;">Currency<br>
      </td>
      <td style="vertical-align: top; width: 239px;">{% for i in stat.3|get_range %}
            <img style = "width: 35px;height: 35px;" src ="{% static 'polls/images/star.png' %}"></img>
            {% endfor %}
      </td>
    </tr>
  </tbody>
</table>
<br>

</div>
{% endblock %}

mysite/polls/templates/polls/welcome.html
<!-- author sri harsha ganja
     ganjash -->
{% extends "polls/base.html" %} {% block extras %}
{% load staticfiles %}
<text
	style="color: black; height: 24px; font-weight: bold; text-decoration: underline; margin-top: 0px; text-align: right; position: relative; right: 500px;">
	
<a href="{% url 'polls:welcome'  %}"> <big>Home</big></a> 
</text>
<text
	style="color: black; height: 24px; font-weight: bold; text-decoration: underline; position: relative; left: 500px; margin-top: 0px; text-align: right;">
<a href="{% url 'polls:logout'  %}"> <big>Logout</big></a> </text>
{% endblock %} {% block content %}

<br>

<div >
<div style="text-align: justify; margin-left: 170px; background-color: beige; border-radius: 25px; padding: 30px 30px 10px; width: 900px;">
<p style="text-align: center; font-weight: bold;"> <big> <big
style="margin-top: 0px; height: 51px;">How to play ?</big></big></p>
<p style="text-align: center;"><big style="text-decoration: underline;"><br>
</big></p>
<p style="text-align: center;"><big style="text-decoration: underline;">Phase
1</big><br>
</p>
<p>Matching the artifacts.<br>
</p>
<p> There are total of four artifacts in each country:<br>
1.Monument<br>
2.National Flag<br>
3.Currency<br>
4.National Animal</p>
These artifacts are designated with a moving number on the side of the
image this moveable number goes in to the appropriate circle in the map
once all the numbers are in the map circles we can click on the blue
button below to place it if the answers are correct the user will be
proceeding to next country or level if the answer is wrong the player
goes back to main screen after system shows which once are wrong and
he/she needs to play the same country or level again. <br>
<br>
Monument&nbsp;&nbsp;&nbsp;&nbsp; :&nbsp;&nbsp;&nbsp; 1 &nbsp;&nbsp;
This number goes where that particular monument is located<br>
National Flag : &nbsp;&nbsp; 2 &nbsp;&nbsp; This number goes where the
capital of the country
located.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp; &nbsp; in&nbsp; the country.<br>
Currency &nbsp; &nbsp;&nbsp;&nbsp;&nbsp; : &nbsp;&nbsp; 3 &nbsp;&nbsp;
This number goes where the currency is made in the country.<br>
Animal&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
:&nbsp;&nbsp;&nbsp; 4 &nbsp;&nbsp; This number goes where that
particular kind of bird or animal is&nbsp; <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp; mostly found in the country.<br>
<br>
For each country the player will be unlocking a free flight ticket to
that country after finishing the level.<br>
<br>
<br>
<div style="text-align: center;"><big
style="text-decoration: underline;">Phase 2<big><big></big></big></big><br>
</div>
<p>Matching the countries.<br>
</p>
<p>If the players finishes the first phase of the game then the player
proceeds to the second phase of the game, in the second phase the
player needs to remember all the flags, monuments, national birds or
animals and national flags which he/she placed properly in the first
phase.</p>
<p>In this phase of the game players are given with country names on
one side and depending on the level national flags, monuments, currency
or national birds or animals on the other side and drop box are placed
in the middle.</p>
<p>Players goal is to match the artifact which belongs to that
particular country and then after matching all the artifacts the player
needs to press match it if the answer is correct the player gets a gold
star and if the answer is wrong player gets a red star and he/she needs
to repeat the level again and if he/she matches all the artifact
correctly they will proceed to next level. When the user get all the 20
stars he/she will be earning a charted flight.&nbsp;&nbsp; <br>
</p>
 
	</div>
</div>

<br><br>
{% endblock %}

mysite/polls/templates/polls/welcome2.html
<!-- author sri harsha ganja
     ganjash -->
{% extends "polls/base.html" %} {% block extras %}
{% load staticfiles %}
<text
	style="color: black; height: 24px; font-weight: bold; text-decoration: underline; margin-top: 0px; text-align: right; position: relative; right: 500px;">
	
<a href="{% url 'polls:welcome'  %}"> <big>Home</big></a> 
</text>
<text
	style="color: black; height: 24px; font-weight: bold; text-decoration: underline; position: relative; left: 500px; margin-top: 0px; text-align: right;">
<a href="{% url 'polls:logout'  %}"> <big>Logout</big></a> </text>
{% endblock %} {% block content %}
<div
	style="height: 51px;">

	<p >
		<big style="text-decoration: underline;"> <big
			style="margin-top: 0px; height: 51px;"><big>Welcome !!!</big></big></big>
	</p>
</div>
<br>
<br>
<div
style="height: 312px; text-align: justify; margin-left: 540px; width: 312px;">
<table style="text-align: center; width: 187px; height: 175px; "
border="0" cellpadding="2" cellspacing="2">
<tbody>
<tr>
<td style="vertical-align: top;"><button class="btn main" id="actionx" > Play </button></td>
</tr>
<tr>
<td style="vertical-align: top;"><button class="btn main" id="actiony" ">Stats</button></td>
</tr>
<tr>
<td style="vertical-align: top;"><button class="btn main" id="actionz">Help !</button></td>
</tr>
</tbody>
</table>
&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; <a
href="http://localhost:8000/game/phase1/"><br>
</a></div>
{% endblock %}

mysite/polls/templates/polls/welcome3.html
<!-- author sri harsha ganja
     ganjash -->
{% extends "polls/base.html" %} {% block extras %}
{% load staticfiles %}
<text
	style="color: black; height: 24px; font-weight: bold; text-decoration: underline; margin-top: 0px; text-align: right; position: relative; right: 500px;">
	
<a href="{% url 'polls:welcome'  %}"> <big>Home</big></a> 
</text>
<text
	style="color: black; height: 24px; font-weight: bold; text-decoration: underline; position: relative; left: 500px; margin-top: 0px; text-align: right;">
<a href="{% url 'polls:logout'  %}"> <big>Logout</big></a> </text>
{% endblock %} {% block content %}
<div
	style="height: 51px;">

	<p >
		<big style="text-decoration: underline;"> <big
			style="margin-top: 0px; height: 51px;">Welcome !!!</big></big>
	</p>
</div>

<br>

<div style="height: 312px; text-align: justify; margin-left: 250px;">
	<p>
		Welcome to the game of maps.<br> Who ever wins&nbsp; will be
		given a prize money of $ 1,000,000 and a free trip to Hawaiian
		islands. So get ready !! <br>
	</p>
	<p>
		The game is to be played in phases. <br>
	</p>
	<p>One after the other , totalling 5.</p>
	<p>If you lose in any one of the games, you have to go back home
		and can't play again.</p>
	<p>If you win in a phase, you will be progressed on to the next
		phase , till the final Round.</p>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	So, get Ready !!!!!!!!<br>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	Click button to continue&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;
	&nbsp;&nbsp; 
	<a href="{% url 'polls:phase1'  %}">  
	<img style="width: 30px; height: 32px;" src="{% static 'polls/images/next.jpg' %}"/>
	</a>
</div>


{% endblock %}